/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author rafin
 */
public class consultaGeralPanel extends javax.swing.JPanel {
    private HomePage homePage;

    /**
     * Creates new form consultaGeralPanel
     */
    public consultaGeralPanel() {
        initComponents();
        
        String caminho  = "src/uteis/logofatec.png";
        ImageIcon logofatec = new ImageIcon(caminho);
        Image ImagemLogoRedimensionada = logofatec.getImage().getScaledInstance(130, 50, Image.SCALE_SMOOTH);
        ImageIcon logofatecRedimensionado = new ImageIcon(ImagemLogoRedimensionada);
        lbLogoFatec.setIcon(logofatecRedimensionado);
    }
    public consultaGeralPanel(HomePage hp){
        this();
        this.homePage = hp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaGeralPanel = new javax.swing.JPanel();
        jLabelCon1 = new javax.swing.JLabel();
        lbLogoFatec = new javax.swing.JLabel();
        btnVoltarLis = new javax.swing.JButton();
        btnListarProcessos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcessos = new javax.swing.JTable();

        consultaGeralPanel.setBackground(new java.awt.Color(255, 255, 255));
        consultaGeralPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabelCon1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCon1.setForeground(new java.awt.Color(0, 128, 96));
        jLabelCon1.setText("Visão Geral de Processos Seletivos");

        btnVoltarLis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVoltarLis.setForeground(new java.awt.Color(0, 51, 255));
        btnVoltarLis.setText("Voltar");
        btnVoltarLis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLisActionPerformed(evt);
            }
        });

        btnListarProcessos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListarProcessos.setForeground(new java.awt.Color(0, 153, 0));
        btnListarProcessos.setLabel("Atualizar Lista");
        btnListarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProcessosActionPerformed(evt);
            }
        });

        tabelaProcessos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaProcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Curso", "Nome do Curso", "Nome da Disciplina", "Código do Processo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProcessos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaProcessos);
        if (tabelaProcessos.getColumnModel().getColumnCount() > 0) {
            tabelaProcessos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProcessos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProcessos.getColumnModel().getColumn(2).setResizable(false);
            tabelaProcessos.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout consultaGeralPanelLayout = new javax.swing.GroupLayout(consultaGeralPanel);
        consultaGeralPanel.setLayout(consultaGeralPanelLayout);
        consultaGeralPanelLayout.setHorizontalGroup(
            consultaGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeralPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(consultaGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(consultaGeralPanelLayout.createSequentialGroup()
                        .addComponent(jLabelCon1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLogoFatec, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultaGeralPanelLayout.createSequentialGroup()
                        .addComponent(btnListarProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltarLis)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        consultaGeralPanelLayout.setVerticalGroup(
            consultaGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCon1)
                    .addComponent(lbLogoFatec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consultaGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarLis)
                    .addComponent(btnListarProcessos))
                .addGap(389, 389, 389))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultaGeralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultaGeralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLisActionPerformed
        homePage.mostrarPainel("Consultas");
    }//GEN-LAST:event_btnVoltarLisActionPerformed

    private void btnListarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProcessosActionPerformed

    }//GEN-LAST:event_btnListarProcessosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarProcessos;
    private javax.swing.JButton btnVoltarLis;
    private javax.swing.JPanel consultaGeralPanel;
    private javax.swing.JLabel jLabelCon1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLogoFatec;
    private javax.swing.JTable tabelaProcessos;
    // End of variables declaration//GEN-END:variables
}
